swipe:
  3:
    left:
      sendkey: LEFTMETA+DOT # Switch workspace next
    right:
      sendkey: LEFTMETA+COMMA # Switch workspace back
    up:
      sendkey: LEFTMETA+LEFTSHIFT+N # Unminimize
    down:
      sendkey: LEFTMETA+N # Minimize
  4:
    left:
      sendkey: LEFTMETA+LEFTSHIFT+TAB # Switch tab back
    right:
      sendkey: LEFTMETA+TAB # Switch tab
    up:
      sendkey: LEFTMETA+LEFTSHIFT+M # Focus
    down:
      sendkey: LEFTMETA+LEFTSHIFT+M # Focus
#pinch:
#  in:
#    sendkey: #
#  out:
#    sendkey: #
hold:
  4:
    sendkey: LEFTMETA+L # Lock
interval:
  swipe: 0.75
  hold: 1.5